[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>", "OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "TBD"
name = "swc_core"
license = "Apache-2.0"
edition = "2021"
repository = "https://github.com/swc-project/swc.git"
version = "0.1.0"

[features]
### Public features
### Users should opt in necessary features explicitly

## General
# Enable `quote!` macro support.
quote = ["swc_ecma_quote"]

## Plugins
# Top level features should be enabled to write plugins for the custom transform.
plugin_transform = [
  # Dependent features
  "__common",
  "__ast",
  "__visit",
  # Enable optional packages
  "swc_common/plugin-mode",
  "swc_plugin_proxy/plugin-mode",
  "swc_plugin_macro",
  "swc_plugin"
]

### Internal features
### Feature sets public features rely on.
### This is not supposed to be used directly, and does not gaurantee
### stability across each versions.

# Common
__common = ["swc_common"]

# TODO: Should this be public?
# AST
__ast = ["swc_ecma_ast/rkyv-impl", "swc_atoms"]
__visit = ["swc_ecma_visit"]

[dependencies]
swc_atoms = { optional = true, version = "0.3.1", path = "../swc_atoms" }
swc_common = { optional = true, version = "0.26.0", path = "../swc_common" }
swc_ecma_ast = { optional = true, version = "0.89.1", path = "../swc_ecma_ast" }
swc_ecma_quote = { optional = true, version = "0.30.0", path = "../swc_ecma_quote" }
swc_ecma_visit = { optional = true, version = "0.75.0", path = "../swc_ecma_visit" }
swc_plugin = { optional = true, version = "0.88.2", path = "../swc_plugin" }
swc_plugin_macro = { optional = true, version = "0.8.1", path = "../swc_plugin_macro" }
swc_plugin_proxy = { optional = true, version = "0.17.0", path = "../swc_plugin_proxy" }
