[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "SDK for authoring swc plugin"
documentation = "https://rustdoc.swc.rs/swc_plugin/"
edition = "2018"
license = "Apache-2.0"
name = "swc_plugin"
repository = "https://github.com/swc-project/swc.git"
version = "0.88.2"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
bench = false

[features]
default = ["plugin_transform_schema_v1"]
plugin_transform_schema_v1 = ["swc_common/plugin_transform_schema_v1"]
plugin_transform_schema_vtest = ["swc_common/plugin_transform_schema_vtest"]

[dependencies]
swc_common = { version = "0.26.0", path = "../swc_common", features = [
  "plugin-mode",
] }
