[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>", "OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Internal sharable storage for the comments between host to the plugin"
name = "swc_plugin_comments"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"
repository = "https://github.com/swc-project/swc.git"

[feature]
# swc/core, which runs plugin
host = []
# actual wasm plugin binary
guest = []


[dependencies]
scoped-tls-hkt = "0.1.2"
rkyv = "0.7.36"
swc_common = { version = "0.17.0", path = "../swc_common", features = [
  "plugin-base",
] }
